apiVersion: v1
kind: Service
metadata:
  name: real-estate-backend-service
  namespace: real-estate-app
  labels:
    app: real-estate-backend
spec:
  selector:
    app: real-estate-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP