apiVersion: v1
kind: ConfigMap
metadata:
  name: real-estate-config
  namespace: real-estate-app
data:
  NODE_ENV: "production"
  PINECONE_ENVIRONMENT: "us-east-1"
  PINECONE_INDEX: "real-estate"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
